### ISSUE TITLE
gameTime available to Console.Update()

### ISSUE THREAD

**Issue by drock07** [Thraka/SadConsole#10]
I noticed that in the sample games, the gameTime is figured out manually inside the custom console classes. Is there a reason it can't be passed down to the consoles as a parameter?

The Engine receives it in its Update method. It could pass it to the ConsoleRenderStack.Update, which would then pass it to the individual consoles' update methods. 

It seems like any game and console would benefit from having the gameTime available. Was it a conscious choice to not include it? Maybe to simplify it?

If not, I could make the change and submit a pull request.

**Comment by Thraka** [comment]
The sample games were written a few years ago by someone else and it must just be what they chose to do. The engine actually stores the Update and Render times each call. I found this more efficient than passing it around to every method that wanted to know how much time had passed for rendering and update. :)

These two properties store the `GameTime.ElapsedGameTime.TotalSeconds` object passed to the respective `Render` and `Update` methods.
* [Engine.GameTimeElapsedUpdate](https://github.com/Thraka/SadConsole/blob/master/SadConsole.Core/Engine.cs#L43)
* [Engine.GameTimeElapsedRender](https://github.com/Thraka/SadConsole/blob/master/SadConsole.Core/Engine.cs#L48)

These two properties are the actual MonoGame `GameTime` objects sent to the Game class.
* [GameTimeUpdate](https://github.com/Thraka/SadConsole/blob/master/SadConsole.Core/Engine.cs#L53)
* [GameTimeDraw](https://github.com/Thraka/SadConsole/blob/master/SadConsole.Core/Engine.cs#L58)

**Comment by Thraka** [comment]
Let me know if this works for you or you need anything else. Thanks for using SadConsole :D
