### ISSUE TITLE
Make a progress bar. Console or game object?

### ISSUE THREAD

**Issue by slinger77** [Thraka/SadConsole#113]
Hi there! 
I am trying to build such an interface:
![image](https://user-images.githubusercontent.com/25457321/32145004-c5e13f64-bcd2-11e7-82eb-79bb765a090f.png)
At the end of the process, i should have UI where a lot of such interfaces will be added to the same screen. 
What would be the correct way of doing that? Use a console and print on it or use game objects? 

Boris

**Comment by Thraka** [comment]
SadConsole has a controls ui system that can be used when your console inherits from `SadConsole.ControlsConsole`. There is a tutorial related to controls available [here](https://github.com/Thraka/SadConsole/wiki/Controls-overview). Using a gameobject for something is handy just because it lets you move it around without having to undraw it's previous location. The controls system is similar to gameobject but handles a lot of input for you, like using buttons and slider controls, things like that.

I could make you a progressbar relatively fast. It's probably something sadconsole needs anyway.

**Comment by slinger77** [comment]
Hi Andy,

Thx for a rapid replay. I am going to check this tutorial tonight, i believe it would be pretty informative.  
I am working with stock market and real time tick quotes will be connected to this bar thus it is not really a progress bar, it is more like an indicator. Main important thing is that this progress bar must be extremely quick and fast! Few thousands of ticks per second can occur! Is it really possible? 
If you can make this control-progress-bar for me - i would love it! 

Boris

**Comment by Thraka** [comment]
Add this file to your project. It's completely self contained. When SadConsole updates in the future, this will be included and you should delete this file from your project. 

https://gist.github.com/Thraka/f6fb7e3fa634e1eba46d6ffaca56ff3d

You can customize the colors of the bar at [line 303](https://gist.github.com/Thraka/f6fb7e3fa634e1eba46d6ffaca56ff3d#file-progressbar-cs-L303).

**Comment by slinger77** [comment]
Great!
Where exactly should i put this file? I use demo project DirectX. I use DosConsole which is really great and i also add other consoles and controls to it.
Which folders can i safely remove from the solution which i don't really need like Desktop GL, Shared code etc.?

**Comment by Thraka** [comment]
Just add it to your project anywhere. As long as it's added, it will be picked up and be usable.

So you're using the source code directly? Or you just copied out the demo project and you're not using all of sadconsole source?

**Comment by slinger77** [comment]
Ok, i've got it! Now i understand where to locate it. I am not using all these projects, sample games, opengl and stuff like that. I use SadConsole-master as the environment then i place my classes in DemoProject and run the software. DosConsole is the blueprint. Later i will add other controls like progress bars, list, selects and so on. This is all i need. Now I just don't have right information how to safely delete unnecessary components which make the project very big and heavy. If there is any tutorial how to do that and not harm the project - it would be so good!

**Comment by Thraka** [comment]
The demo project is using the sadconsole library directly. If you want to simplify it, remove that project reference from the demo project. You can then add the nuget package reference to the demo project. If you do this, you can remove all projects except the demo project dx and demo shared project.

**Comment by slinger77** [comment]
I will try but later. Now i need to handle new control which you just prepared for me. After that, we will see what happens. Now i need to set up my git account in order for being able to receive your future update which will contain that new file (progress bar). I did not set it up. I just downloaded the project and started using it. I am not sure if you publish a new version of SadConsole i am going to be able to use it without losing my code. It is still pretty complicated.

**Comment by Thraka** [comment]
Nuget is used to distribute new versions of sadconsole, so you don't need to use the source code. https://www.nuget.org/packages/SadConsole/

**Comment by slinger77** [comment]
This control is great! 
![image](https://user-images.githubusercontent.com/25457321/32412600-03b91a92-c20e-11e7-8988-7b6ca0a0bd13.png)
Is it possible to make it vertical? I did not find this property.
Why is progress property float? It would be easier to use percents or just a value from a to 0 to 100. Now i am trying to hook this progress bar to stock quotes. We will see how fast is it.

**Comment by Thraka** [comment]
A 0.0 - 1.0 float is a percent value really :) If you have a 1-100 value just divide by 100f to get your converted 0.0-1.0 value

You can make it vertical in the constructor, after width/height pass in a `System.Windows.VerticalAlignment` value.

**Comment by slinger77** [comment]
Thank you very much! I will try do apply given information which sounds pretty useful!
