### ISSUE TITLE
Right version of SDL2.dll

### ISSUE THREAD

**Issue by ernespn** [Thraka/SadConsole#115]
In https://github.com/Thraka/SadConsole/wiki/NuGet-Starter-MonoGame you are providing a SDL2.dll file. which didn't work for me getting a "System.BadImageFormatException An attempt was made to load a program with an incorrect format"
I downloaded the right version (32bit) from here https://www.libsdl.org/download-2.0.php.
Just in case someone else will run to the same problem

**Comment by Thraka** [comment]
Thanks! I've updated the wiki.
