### ISSUE TITLE
Typo: InputBoxes have *carets* not *carrots*

### ISSUE THREAD

**Issue by G3Kappa** [Thraka/SadConsole#120]
[File](https://github.com/Thraka/SadConsole/blob/9d3d9ee22edef7e61f841c1164b43e1be4a291a4/src/SadConsole.Shared/Controls/InputBox.cs)

There you'll find multiple "Carrots" although this isn't a garden.

**Comment by Thraka** [comment]
hahaha wow thanks! I'll get that adjusted.
