### ISSUE TITLE
Surface Size and Render Area Possibilities

### ISSUE THREAD

**Issue by NineSigma** [Thraka/SadConsole#121]
I'm new to all of this so it's not clear to me whether this is a bug, something I don't comprehend, a case of missing training wheels, or some combination of all.

A class (inheriting from SadConsole.Screen) called MasterScreen is instantiated in the initialization scheme suggested by tutorials.

`SadConsole.Game.OnInitialize = Init;
...
SadConsole.Game.Instance.Run();`

In the Init Function:

`masterScreen = new MasterScreen();
            masterScreen.LoadMap(new Map(A, B));`
*A and B are just fake names for me to reference here.

The LoadMap function of MasterScreen fills an instance of a MapScreen (another SadConsole.Screen created in the constructor of MasterScreen) and makes it a child.

`surface = new BasicSurface(map.width, map.height, map.GetCells(), SadConsole.Global.FontDefault, new Rectangle(0, 0, C, D));` ***
`drawCall = new SadConsole.DrawCallSurface(surface, position, false);`

and later

`public override void Draw(TimeSpan timeElapsed) {  renderer.Render(surface);...`

A and B are the x and y dimensions of a Map object which is ultimately rendered to the screen. C and D are the size of the MapScreen, the screen real estate taken up by the mapScreen object. 

It's clear to me that the intended design is that (A,B) is a bigger rectangle than (C,D) - I just want to point out that I do at least understand that.

There are some strange behaviors regarding (A B) < (C D). I noticed it at first because of a wild programming error regarding indices of my Map object. If (C,D) is (75,46), you can actually build and run the project and it will render... something weird all the way down to (A,B) = (7,46). The rendering just keeps "wrapping" in the increasing x direction, though with each successive "wrap" the corresponding y values get shifted by -1.

`aaabbbccc`
`bbbcccddd`
`cccdddeee`
`dddeeefff`
![surfaceandrenderissue](https://user-images.githubusercontent.com/37239889/37241809-74ee56ba-242d-11e8-8d06-0d59cd8efd41.png)

[This is a 7x46 "room" of tiles with a wall on the outermost border and another wall at y=5 to demonstrate the wrapping effect.]

However, if B is even 1 less than D, you get an out of bounds exception on surface in the line marked *** above. In addition to that, when "wrapping", if the y values are shifted negative enough for you to eventually see the equivalent of B < D, you also get the same out of bounds exception.

I was utterly lost when this first happened and assumed it was because I was improperly converting my 2d array of MapTiles to a 1d array of SadConsole.Cells (however, it turned out I was doing the conversion correctly). I started digging into the code and even noticed that there was care taken to manage Surfaces.RenderArea that I glanced over and assumed should be taking care of things like out of bounds issues. Though admittedly most of the Surfaces and Rendering code is well above my pay grade for now.

It seems to me that this shouldn't be default behavior when it comes to viewport vs. surface size issues.

**Comment by Thraka** [comment]
This shouldn't be happening. If `C` and `D` are bigger than `map.Width` and `map.Height`, an exception should be thrown. The strange wrapping pattern is probably from the cell array being incorrect. I would have to see more of your code to be sure. Perhaps some debug shots that show the values of the variables at map creation.

**Comment by NineSigma** [comment]
Hi, Thraka. So I started up Visual Studio today, having made no code changes (as far as I know) since the screenshot of the post above was taken, and (A,B) < (C,D) doesn't work in either dimension now, returning an out of bounds exception as seems appropriate. 

![grt100x56](https://user-images.githubusercontent.com/37239889/37249148-a5bbc57a-24af-11e8-9a33-2916ceb1c24c.png)
![grt100-25x56-10](https://user-images.githubusercontent.com/37239889/37249149-aa8aa2d8-24af-11e8-9b97-c01a2dfd7516.png)

You can see from the attached screenshots that the code appears to work. The second image has the (A,B) = (C,D) through an offset and going even 1 beyond returns an out of bounds exception. I've never used any kind of big IDE before so (in order to maintain my sanity) I would have to guess it was something to do with Visual Studio needing to be closed and reopened.

Thanks for your work on the project, by the way. I've found it very helpful, though at my level some things are fairly impenetrable.

**Comment by Thraka** [comment]
In all my years of Visual Studio (1998) I've never seen it run the "wrong" executable. 😄 

If you had a compile error and it prompted you to run anyway, and you accepted, it would have run the last version compiled version. Perhaps you ran into that scenario. Anyhoo, glad you're up-and-running.
