### ISSUE TITLE
How to use GameObject?

### ISSUE THREAD

**Issue by KarateSnoopy** [Thraka/SadConsole#126]
I can't get a GameObject to render.  I can get box, line, and circle working fine.  

I must be doing something wrong, but can't figure it out.  It just doesn't render.  I'm compiling against the latest source in master.  I've stepped into the gameObject.Draw() call and it looks right, but it doesn't render I must be doing something wrong.   Any idea?  Thanks

Here's what I'm doing:

```
    public class Game1 : SadConsole.Game
    {
        SpriteBatch spriteBatch;
        SadConsole.Console _console;
        SadConsole.GameHelpers.GameObject gameObject;

        public Game1() : base("Fonts/IBM.font", 240, 68, null)
        {
            Content.RootDirectory = "Content";
            GraphicsDeviceManager.IsFullScreen = true;
        }

        protected override void Initialize()
        {
            IsMouseVisible = true;
            base.Initialize();

            _console = new SadConsole.Console(120, 34);
            SadConsole.FontMaster fontMaster = SadConsole.Global.LoadFont("Fonts/IBM.font");
            _console.TextSurface.Font = fontMaster.GetFont(SadConsole.Font.FontSizes.Two);

            gameObject = new SadConsole.GameHelpers.GameObject(1, 1);
            gameObject.Animation.CurrentFrame[0].Glyph = '@';
            gameObject.Animation.CurrentFrame[0].Background = Color.Red;
            gameObject.Animation.CurrentFrame[0].Foreground = Color.White;
            gameObject.Animation.IsDirty = true;
            gameObject.IsVisible = true;
            gameObject.Position = new Point(20, 20);

            SadConsole.Global.CurrentScreen.Children.Add(_console);
        }

        protected override void LoadContent()
        {
            spriteBatch = new SpriteBatch(GraphicsDevice);
        }

        protected override void UnloadContent()
        {
        }

        protected override void Update(GameTime gameTime)
        {
            gameObject.Update(gameTime.ElapsedGameTime);
            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);
            base.Draw(gameTime);
            gameObject.Draw(gameTime.ElapsedGameTime);
        }
    }
```

**Comment by Thraka** [comment]
This has to do with how you're using SadConsole. When the `SadConsole.Game` gets created it adds two components. 

1. [ClearScreenGameComponent](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Graphics.MonoGame/ClearScreenGameComponent.cs)  
This calls `GraphicsDevice.Clear` and uses the color defined in `SadConsole.Settings.ClearColor`.

2. [SadConsoleGameComponent](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Graphics.MonoGame/SadConsoleGameComponent.cs)  
This does all of the rendering/update logic for SadConsole things based (mostly) on the `SadConsole.Global.CurrentScreen` object.

The way the `SadConsoleGameComponent` works is that when `Draw` is called (which is invoked by your `base.Draw(gameTime)` line, the following happens:

1. Clears the previous set of draw calls (a draw call is a individual draw routine to build the final screen presented in the game by sadconsole)
2. Runs through all of `SadConsole.Global.CurrentScreen` gathering draw call objects in the `SadConsole.Global.DrawCalls` collection.
3. Runs through all of the draw call objects that have been gathered, building the final screen texture on `SadConsole.Global.RenderOutput`
4. Draws `SadConsole.Global.RenderOutput` to the actual window.

So when you do `gameObject.Draw()` **AFTER** and **OUTSIDE** of `base.Draw` you've just queued up the draw call for the next pass. However, at the start of that next pass, the drawcalls collection is cleared (step 1), throwing away your draw request. 

When you add an object to the `CurrentScreen` it will have `Update` and `Draw` (which queues up that draw call for the object) called on it automatically. Add the gameobject as a child of the `_console` (it will be positioned relative to it) or the `CurrentScreen`. Remove your override Draw/Update methods.

If you need to inject yourself in the middle of that process there are a few things you can do.

1. Use the `SadConsole.Game.OnDraw = DrawMethod;` variable to use a method defined like your override Draw (but dont use an override). This `DrawMethod` is invoked between steps 1 and 2 above. This lets you manipulate the drawcall collection as you need.

2. Remove the `SadConsoleGameComponent` from the game class, provide all of your own drawing routines. Obviously not much benefit to this and a lot of extra work for you ;)

**Comment by KarateSnoopy** [comment]
Ah, got it working.  Thanks for the info! :)
