### ISSUE TITLE
ProgressBar Customization

### ISSUE THREAD

**Issue by NineSigma** [Thraka/SadConsole#127]
I have a progress bar that properly tracks progress by a method called in the overriden Update() function like so:

[StatusScreen.cs]
`public override void Update(TimeSpan timeElapsed)  {`
`            this.UpdateStatus();`
`            base.Update(timeElapsed);}`

[StatusScreen.cs/UpdateStatus()]
`playerHealthBar.Progress = (float)d.currentHP / (float)d.maxHP;`
...
`this.playerHealthBar.Position = new Point(1, 3);`

Not only does the progress bar update correctly, but it also positions correctly relative to its ControlsConsole parent.

What I'm struggling with is changing the appearance of it. Ideally I'd want it to use a different font, but at the moment I'm stuck with just changing even its color. It does not inherit its color from the ControlsConsole because the rest of that is filled with green text at the moment (the progress bar is white, foreground and background).

I noticed it has a TextSurface and tried:
`this.playerHealthBar.TextSurface.DefaultForeground = Colors.greenText;`
but that seems to have no effect.

I looked deeper into the code and found that it refers to two private Cells for its appearance. These cells reference its theme. A ProgressBarTheme is made up of two ThemePartBase objects, foreground and background. A ThemePartBase is made up of several public Cells - Normal, Disabled etc.

On that basis I tried:
[StatusScreen.cs Constructor]
`ThemePartBase themePart = new ThemePartBase  {`
`                Normal = new Cell(Colors.greenText, Colors.greenText, 'k') };`
`ProgressBarTheme theme = new ProgressBarTheme {`
`                Foreground = themePart,`
`                Background = themePart  };`

Merely as a test to see if I could get it look different, and it still has no effect. It's clear that I'm missing something, and I wanted to know what the intended route is towards customization regarding font(size etc.) and color.

**Comment by NineSigma** [comment]
Navigating this library does not bring out the best in me. The color issue was failing due to a simple initialization error. I have it working now.

I'm still stuck on the font issue. There is an AlternateFont property of the ProgressBarTheme, and it clearly works since I can see the "thatch" glyph change when I change the font. I am interested primarily in changing the size of the ProgressBar with respect to its surroundings (e.g. to make it half-sized so it takes up half the vertical space), but loading a different-sized font seems to have no effect.

Is loading an alternate font with a different size not the correct course here? Is there another way to change the size of the ProgressBar?

**Comment by Thraka** [comment]
Sorry for the delay, I've been unavailable the last few days.

Correct, you should not load an alternate font that is of a different size. I believe that will mess up positioning and any sort of mouse detection on it (I don't think it uses any input though).

Can you confirm which version of SadConsole you're using?

I need to write an article on theme changes. There are two ways to change the theme of the control.

1. For a specific control type, you can change the theme for all instances of it. Set the theme at the start of your program, such as the `SadConsole.Game.OnInitialize = Init` callback.

   ```csharp
   private static void Init()
   {
       // your other init code ...
   
       SadConsole.Themes.Library.Default.ProgressBarTheme.Background.Normal = new SadConsole.Cell(new Color(102, 204, 255), new Color(51, 102, 153));
       SadConsole.Themes.Library.Default.ProgressBarTheme.Background.Normal.Glyph = 176;
       // ... all the other "SadConsole.Themes.Library.Default.ProgressBarTheme." states.
   }
   ```

2. Change the theme for a specifc control instance, kind of like you were doing

   ```csharp
   var myTheme = new SadConsole.Themes.ProgressBarTheme();
   myTheme.Background = new SadConsole.Themes.ThemePartBase();
   myTheme.Background.Normal = new SadConsole.Cell(new Color(102, 204, 255), new Color(51, 102, 153));
   myTheme.Background.Normal.Glyph = 176;
   // ... The rest of the background/foreground states ...
   
   this.playerHealthBar.Theme = myTheme;
   ```

   There was a bug that was fixed about a month ago (and the fix was released to NuGet) where when you change the theme (with `controlVar.Theme = themeVar`) the control wouldn't visually know it changed. If you're not using the latest SadConsole, you need to call both `controlVar.DetermineAppearance();` and `controlVar.Compose();`.

**Comment by NineSigma** [comment]
Thanks for your response, Thraka. That is very interesting about changing the defaults! It didn't occur to me, though I've seen a similar pattern for other things throughout the library. I'm using 6.4.10 and did not experience the bug you described - I actually updated a while back when I first read about that bug (I believe it was here in the issues section).

So for particular instances, constructing a new theme from the ThemePartBases is your recommended route. I've gotten that to work with regards to color and glyph, but I'm missing how to control the size of the ProgressBar. As an example, have a 9x9 ProgressBar drawn over a region with a 15x15 font.

I've tried many different things, and the only one that actually worked was to change the font size of the ControlConsole which the ProgressBar is added to. However, that method is less than ideal since my initial concept involved one ControlConsole with multiple ProgressBars, each of varying dimension. Does that concept lie outside the design of ControlConsoles/ProgressBars?

I love the controls, by the way. I actually think they are some of the most useful parts of the library.

**Comment by Thraka** [comment]
At the bottom of the comment box is a **Styling with Markdown is supported** link. Anyway, it's called a code fence and looks like this (using a backtick, not an apostrophe)

\```csharp
my code
\```

Are you trying to "zoom" the progress bar? When you create the progress bar you choose the width and height. So you could create a 1x10 vertical bar that is thin looking, and then also create a 2x10 vertical bar that looks a little thicker. 

Maybe if you took a screenshot and possibly draw on it to show what you mean.

**Comment by NineSigma** [comment]
![progressbarsizeq](https://user-images.githubusercontent.com/37239889/38131957-0526bfd4-33d7-11e8-8022-2750e3d19cac.png)

Apologies for the ambiguity.

This is a blown-up image with some copy-paste magic. The bottom-most lines are the current state of the ProgressBar size and the top-most visual representation is what I'm looking for. I'm obviously looking for a clean font-based solution so that everything is pixel perfect - not some kind of image stretching business.

My initial idea was that providing an AlternateFont that's smaller would get this effect, but that doesn't actually change the rendered size of the ProgressBar. 

My current design has one ControlsConsole and multiple ProgressBars. Through some messing around, it seems that the rendered size of a ProgressBar is coupled unavoidably to the "correct" font size of its ControlsConsole. If that is the case, I would need to make one ControlsConsole per each different size. I would like to avoid that for 2 reasons:

a) The code would be a lot cleaner and more clear.
b) It represents a significant rewrite/redesign.

My question (as I currently understand it) boils down to: is there a way to decouple the rendered size of a ProgressBar from the font used by its ControlsConsole?

Or perhaps is there a different way altogether to get what I'm looking for?

**Comment by Thraka** [comment]
Sorry, I've been sick the last two days and I haven't been out of bed. The [ControlsConsoleRenderer.RenderControls](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Renderers/ControlsConsoleRenderer.cs#L67) method handles drawing each control. Currently it determines the destination drawing size based on the surface the control is used with.

I don't see an easy way for you to do this at the moment. I have done something similar though with two regular consoles, one double in size, the other smaller. I just had them drawing on top of each other. 

You could make your own renderer that perhaps took your scenario into account, but that is obviously a little advanced.

**Comment by NineSigma** [comment]
Thanks for your answer, Thraka. I think the questions have been definitively answered, so I'll close the issue.
