### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by thomasd3** [Thraka/SadConsole#128]
When I get SadConsole from NuGet and I try to run the sample from the Wiki tutorial (https://github.com/Thraka/SadConsole/wiki/How-to-Create-and-Print-on-a-Console), it compiles but I get an instant crash on the first line.

When I download the project and use the code from the samples I can get the display to work, but the calls done for the init are radically different.

So, is there 2 sets of API? is the wiki outdated? I'm a bit confused.

**Comment by Thraka** [comment]
You might be having a conflict with the `System.Console` and the `SadConsole.Console` object types. Try adding a `using Console = SadConsole.Console` directive at the top of your code file.
