### ISSUE TITLE
Multi-line InputBox (a.k.a. InputArea)

### ISSUE THREAD

**Issue by INeedAUniqueUsername** [Thraka/SadConsole#143]
Is there any built-in way to create a multi-line InputBox (a.k.a. InputArea)? Supposedly it would have a maximum height and automatically add a scroll-bar when there's too much text to display at once.

Also, thank you for creating SadConsole.

**Comment by Thraka** [comment]
I've done things like this outside of the controls system, so it's very possible. I've just not added that to the control.

**Comment by Thraka** [comment]
I think I'm going to skip this. The control system doesn't implement the `SadComponent` type of system, which the existing cursor is built on. I don't really feel like duplicating all of that code into another place. I think perhaps v11 or just a control implemented by someone else would be more appropriate.

**Comment by INeedAUniqueUsername** [comment]
Oh yeah I implemented something like this in [UniqueWiki](github.com/INeedAUniqueUsername/UniqueWiki)
