### ISSUE TITLE
SadConsole.GameHelpers.WorldGeneration

### ISSUE THREAD

**Issue by bloodyraoul** [Thraka/SadConsole#149]
Hello, I am using WorldGeneration in my project
It is no more in SadConsole library in 7.0
Should I add it to my project separatly or will it reappears soon ?
Thank you

**Comment by Thraka** [comment]
That is really great to hear that you were using it! I didn't think anyone was, and honestly, it was a bit out of place. I want to create a new library that is a game helper shim between SadConsole and GoRogue and has the world generation built in. It felt out of place in SadConsole core.

I'll fix up the code and upload it so you can add it to your project.

**Comment by Thraka** [comment]
[SadWorldGeneration.zip](https://github.com/Thraka/SadConsole/files/2337620/SadWorldGeneration.zip)

Here is a DLL you can use including the source code.

**Comment by bloodyraoul** [comment]
Thank you very much

**Comment by Chris3606** [comment]
It is worthy of note that SadConsole's above map generation does a good bit more with _overworld_-style map generation than GoRogue does (at the moment :)) so it might be worth keeping around in some form.
