### ISSUE TITLE
`VirtualCursor.IsVisible = true` doesn't allow typing in the console anymore

### ISSUE THREAD

**Issue by darthdeus** [Thraka/SadConsole#152]
I'm watching this video https://www.youtube.com/watch?v=QzOCHFPAon4 about sad console, and at about 9:52 you show that just setting `console.VirtualCursor.IsVisible = true` then allows you to type in the console window. But it doesn't do anything for me, it just shows the cursor. I'm using 6.1.3 if that's relevant.

**Comment by Thraka** [comment]
With the 7.0 release, that property changed to `Cursor` instead of `VirtualCursor` as an FYI.

Keyboard input is only ever given to the "focused" console. You must call `console.IsFocused = true` to give it focus and then the keyboard input will work.

**Comment by Thraka** [comment]
@darthdeus Does this solve your problem?
