### ISSUE TITLE
Theme Coloring, How to change.

### ISSUE THREAD

**Issue by darkfriend77** [Thraka/SadConsole#155]
Hi, I'm working on a project which is using SadConsole as first Gui integration, to test our gameframework before we go for the mobile integration with unity. (blockchain game www.mogwaicoin.org, the World of Mogwais).

I would like to set the standard coloring of our GUI, is there a documentation where it shows how I can create a theme, I would like to change the buttons color, once for all.

Thanx for the help, SadConsole is super great addition for us.

**Comment by Thraka** [comment]
Hi! Glad SadConsole is helping you get your project done :)

The default theme is built when the the `SadConsole.Theme.Library` is first accessed by the controls system. [Theme Appearances](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Themes/Library.cs#L123) are used for the state of the control (such as mouse over). By default, all of the controls use that set of appearances. Once the library themes are built, you can then tweak individual themes, such as a button or a textbox.

That set of appearances though is built from a set of colors defined in the [SadConsole.Theme.Colors](https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/Themes/Colors.cs#L56) class. If one of the first things you do before you really init/start SadConsole is change the colors (`SadConsole.Themes.Colors.ControlBack = Color.Blue`), it should affect all controls when the appearances are first built.

**Comment by Thraka** [comment]
I'm assuming this helped you, I'm going to close this issue, please reopen if there is a problem.
