### ISSUE TITLE
Is there a way to copy paste a text out of SadConsole?

### ISSUE THREAD

**Issue by darkfriend77** [Thraka/SadConsole#158]
Currently I haven't found a way to copy a text out of the SadConsole GUI and I'm going over a log, but maybe there is a way to copy past or copy a definied text to the clipboard.

any option to copy this text instead of having it beeing loged to an file.

**I'm strictly bound to the .NETCore version.** 

![wallet_copypaste](https://user-images.githubusercontent.com/17710198/47425861-e8258880-d78b-11e8-9fc8-d8696783ff32.png)

**Comment by Thraka** [comment]
Are you asking if you can select with the mouse? If so, this is something I was thinking of adding to SadConsole.

Otherwise you'll just have to hook up a keyboard or button to do it. you can do it with the `myConsole.GetString` method.

**Comment by darkfriend77** [comment]
Okay, thank you. Yep, it's about the clipboard access, Maybee I have to code it explicit for windows ... as most of the users are currently windows users.
