### ISSUE TITLE
Positioning a LayeredConsole is not the same as positioning a non-LayeredConsole

### ISSUE THREAD

**Issue by arxae** [Thraka/SadConsole#17]
Same person as on Reddit.

So in the game i'm working on, i need to have a ControlsConsole on the left side. And the map console (a LayeredConsole) should be moved to the right. But it doesn't happen. I have setup a example case.

The 2 consoles in this example should be slightly staggerd. The blue console (a LayeredConsole) is set to position 10, 10. The red console (a ControlsConsole) is set to 15, 15. But as you can see on the screenshot, only the red console is staggered.

Screenshot:
![me0udxq](https://cloud.githubusercontent.com/assets/1032170/14536395/6cc257fe-0272-11e6-80a9-3f27e796a58b.png)

The code is pretty simple:
Program.cs
```
class Program
	{
		[STAThread]
		static void Main(string[] args)
		{
			using (var game = new MyGame())
			{
				game.Run();
			}
		}
	}
```
MyGame.cs
```
class MyGame : Game
	{
		GraphicsDeviceManager graphics;

		public MyGame()
		{
			graphics = new GraphicsDeviceManager(this);

			var sadConsoleComponent = new SadConsole.EngineGameComponent(this, () =>
			{
				SadConsole.Engine.Initialize(GraphicsDevice);

				using (var stream = System.IO.File.OpenRead("Fonts/IBM.font"))
				{
					SadConsole.Engine.DefaultFont = SadConsole.Serializer.Deserialize<SadConsole.Font>(stream);
				}

				SadConsole.Engine.Fonts.Add(SadConsole.Engine.DefaultFont.Name, SadConsole.Engine.DefaultFont, true);

				int width = 50;
				int height = 25;

				SadConsole.Engine.DefaultFont.ResizeGraphicsDeviceManager(graphics, width, height, 0, 0);

				var con1 = new Console1(1, 25, 25) { Position = new Point(10, 10) };
				var con2 = new Console2(25, 25) { Position = new Point(15, 15) };

				SadConsole.Engine.ConsoleRenderStack.Add(con1);
				SadConsole.Engine.ConsoleRenderStack.Add(con2);
			});

			Components.Add(sadConsoleComponent);
		}

		protected override void Draw(GameTime gameTime)
		{
			GraphicsDevice.Clear(Color.Black);
			base.Draw(gameTime);
		}
	}

	public class Console1 : SadConsole.Consoles.LayeredConsole
	{
		public Console1(int layers, int width, int height) : base(layers, width, height)
		{
			CellData.DefaultBackground = Color.Blue;
		}
	}

	public class Console2 : SadConsole.Consoles.ControlsConsole
	{
		public Console2(int width, int height) : base(width, height)
		{
			CellData.DefaultBackground = Color.Red;
		}
	}
```

**Comment by Thraka** [comment]
Ack, I see what is going on. I forgot LayeredConsole is slightly different. I can fix it in code though so it behaves like any other console. 

For now, call [con1.SyncLayers()](https://github.com/Thraka/SadConsole/blob/master/SadConsole.Core/Consoles/LayeredConsole.cs#L89) after you set the Position.

**Comment by arxae** [comment]
Confirmed for working. So basically, if you don't sync the layers, you move the console, but the layers stay in the same relative position, thus making it look like they didn't move?

**Comment by Thraka** [comment]
Well the layered console is kind of like a hack of a bunch of CellRenderer's (which is the a parent class of the Console type) together. So even though the LayeredConsole IS a Console, when it renders/updates, it actually just passes those calls on to the individual layers. I had created a layeredConsole.Move(Point) method which just sets the location and then calls sync for you, but I should really just hook up the Location property to do that for you, so don't use it since I'll fix Position eventually and you can just remove the Sync call. :stuck_out_tongue_winking_eye: 

I'm not happy with it. I need to redo it. Of course it didn't matter when no one was using SadConsole :smile: but now that people are using it I need to be better about design.
