### ISSUE TITLE
Porting to OS X/Linux

### ISSUE THREAD

**Issue by eropple** [Thraka/SadConsole#2]
Hey--

So as per our brief chat on Twitter, I think this library is pretty fantastic; I'm evaluating a few solutions and I think this might scratch my itch for some prototyping I want to get done. I work primarily on a Mac these days, though, so I'd like to look into porting this.

As it currently stands, there are hard deps in all projects on MonoGame.Framework. Which is cool, except (to the best of my knowledge) that means we have either a combinatoric explosion of project files (SadConsole.Core.Windows, SadConsole.Core.MacOS, etc.) or project files rely on external settings and so can't be manipulated in Visual Studio without those settings being destroyed (been there, swore at that).

What I'm wondering about is whether or not it makes sense to build this as a PCL, maybe unifying the various subprojects into one or two, and expecting the user to link the correct version of MonoGame. This was illuminating to me the first time I tried it:

http://www.craftworkgames.com/blog/day-6-running-with-monogame-portable/

**Comment by Thraka** [comment]
Hi Ed, can you fork and check this in? I have another guy who is having trouble getting it to run on Mac and your build would probably help him :)

**Comment by eropple** [comment]
Hey, I never noticed this (but using SadConsole for something else now). I didn't actually change any code, I just swapped the MonoGame assemblies out.

As mentioned in the other thread, due to the wide range of platforms that have a MonoGame dep, it may make sense to do a significant project refactoring for actually making this happen (using a shared project for code and a per-platform .csproj to bind it to the necessary references).

**Comment by eropple** [comment]
The preparatory work for this is in #6.
