### ISSUE TITLE
Redesign entity for a lite scenario

### ISSUE THREAD

**Issue by ghost** [Thraka/SadConsole#249]
The majority of people are using entity in the following way:

1. It's a single cell object.
2. It's not animated with multiple `AnimatedSurface` objects.
3. It's positioned on top of a console.
4. Visibility and positioning are controlled by where it falls on the console view.

A new type should be created that fits this role. Entity should either be changed or renamed to fit the other role of a large animated object.

**Comment by Thraka** [comment]
This has been added to V9
