### ISSUE TITLE
Entity serialization neglects members inherited from Console

### ISSUE THREAD

**Issue by AnotherEpigone** [Thraka/SadConsole#254]
EntitySerialized inherits DataMembers from ConsoleSerialized, but the cast methods ignore those members. The result is that they're written with default values, and ignored when creating a new Entity on deserialization. This includes Font, DefaultForeground, DefaultBackground.

With the way the serialization objects inherit in general it's easy to forget to handle inherited DataMembers, so I suspect this kind of bug may exist elsewhere.

**Comment by Thraka** [comment]
This is solved in v9
