### ISSUE TITLE
Support ColoredString in ListBox theme

### ISSUE THREAD

**Issue by AdrienKYoung** [Thraka/SadConsole#267]
ListBox currently defaults to a theme that supports a <String, Color, Color> tuple, but not a ColoredString (if I understand it correctly, it defaults to using ListBoxItemColorTheme). It would be very helpful for ListBox to support ColoredString out of the box instead of requiring a custom theme.

**Comment by Thraka** [comment]
This is fixed in V9.1.0 that was just released
