### ISSUE TITLE
Mouse position not updated

### ISSUE THREAD

**Issue by arxae** [Thraka/SadConsole#29]
I have been trying to get mouseinput to work, but i only get valid values for the ScreenLocation.
Attached is a screenshot which shows the values in the following format: ConsoleLocation - ScreenLocation - WorldLocation - Console (from MouseInfo)

![image](https://cloud.githubusercontent.com/assets/1032170/16571337/7d8ab626-425a-11e6-8bd7-369c4c2484fe.png)

I have put my code in a repository because i don't know where the issue lies. The repository can be found [HERE](https://github.com/arxae/Phyrric/tree/master/Phyrric)

I check for mouse updates in the GameScreen class. 

In this project i used the 2.5.0.0 Nuget package.

**Comment by Thraka** [comment]
Investigating...

**Comment by Thraka** [comment]
The root of the engine processes the mouse for initial state, and then sends it to the console for more state information. The engine first adds in the screen coordinates and button clicking information. Then it's sent to the console for processing. The console then adds information about the current console (where is the mouse specifically on the console (if it is) and then where on the screen in console coordinates it is).

[Here](https://github.com/arxae/Phyrric/blob/master/Phyrric/GameScreen.cs#L112) where you call `return base.ProcessMouse(info);` you need to move that up higher, like the first thing you do.

What `ConsoleList` does specifically with the mouse is it sends it to each console's `ProcessMouse` method. If the mouse is currently over that console, `ConsoleList` will stop sending the mouse to consoles and return `True`. If the mouse is not over any console, `False` will be returned. Regardless of if the mouse was over a console, whatever console was last processed will be in the info object (console, position, world position).

**Comment by Thraka** [comment]
Oh and obviously instead of calling `return base .... ` save it to a variable and check for true/false.

**Comment by Thraka** [comment]
Let me know if that gets you working. Thanks for using SadConsole. you got some nice clean code there... I was just working on V3 tonight, I'm so close to finishing....

**Comment by arxae** [comment]
Still same result, but i admit i'm having a hard time to know where to check for mouseinput. I actually only need the mouseposition for the map for now. Any advice for this?

And thanks for the positive feedback! Looking forward to V3!

**Comment by Thraka** [comment]
Sorry, I forgot, you need to set `console.CanUseMouse = true;` for each one you want to allow processing.

**Comment by Thraka** [comment]
V3 is going to be a huge amount of breaking changes.... 😭 I've reworked a bunch of core systems to be clearer on intent, hopefully easier to use. But it also opens up a lot of flexibility.

**Comment by arxae** [comment]
CanUseMouse did the trick! Thanks.

Major version change is major version change :P Still looking forward to it, don't hold it back too much longer will you!
