### ISSUE TITLE
ListBox scroll and items desync upon adding an item

### ISSUE THREAD

**Issue by Dodo-Codes** [Thraka/SadConsole#290]
Adding an Item to a ListBox and using ScrollToSelectedItem() afterwards desyncs the scroll and items in the list (scroll is correct, items are not). Manual update is required for that case to work:

```
listBox.Items.Add(item);
listBox.SelectedIndex = logList.Items.Count - 1;
listBox.Update(TimeSpan.Zero); // needed
listBox.ScrollToSelectedItem();
```

**Comment by Thraka** [comment]
Fixed in v10
