### ISSUE TITLE
Small issue with TextBox and Caret

### ISSUE THREAD

**Issue by coldwarrl** [Thraka/SadConsole#296]
In TextBox.cs

```csharp
        protected void ValidateCursorPosition()
        {
            if (MaxLength != 0 && EditingText.Length == MaxLength)
            {
                if (_caretPos > EditingText.Length)
                    _caretPos = EditingText.Length - 1;
            }
         ...
        }
```
` if (_caretPos > EditingText.Length)` should be
` if (_caretPos >= EditingText.Length)` 

else the caret moves right, exceeding MaxLength when typing stuff in the textbox. I tested it, should work fine with the proposed fix :).
@Thraka can also do a PR if you like

**Comment by Thraka** [comment]
@coldwarrl Actually, I think the behavior is correct and that code should be deleted 😁 If the code runs (with your modification, which I think is what is was supposed to do originally) the caret is placed on the last character. If you press backspace, you delete the character behind it, not the last character.
