### ISSUE TITLE
Surface.SetGlyph does not take .IsVisible into account, and still renders the cell regardless

### ISSUE THREAD

**Issue by Ven0maus** [Thraka/SadConsole#298]
```csharp
Surface.SetGlyph(5, 5, new ColoredGlyph(Color.Red, Color.Blue, '@') { IsVisible = false });
```
Current scenario: cell is visible
Expected: cell isn't visible

**Comment by Venom0us** [comment]
A reference to my own scenario where I ran into the problem:
https://github.com/Venom0us/FlowVitae/blob/main/Venomaus.Visualizer/Graphics/MapWindow.cs#L19

**Comment by Venom0us** [comment]
Discussed in discord to just remove the overload in v10
