### ISSUE TITLE
Nuget issue with SadConsole.Core package when .NET < 4.6

### ISSUE THREAD

**Issue by arxae** [Thraka/SadConsole#30]
When installing the SadConsole.Core package through nuget, no references are made (the font files are added correctly).

When trying to add for example the SadConsole.GameHelper package, i receive the following error:
![image](https://cloud.githubusercontent.com/assets/1032170/16671459/c22590c0-449f-11e6-9b8d-53aade7fb5ac.png)

When changing my project to use .NET 4.6, it installs correctly. 
So when the project is < 4.6, then the package installation fails silently

**Comment by Thraka** [comment]
Thanks. I'll have to investigate how to target a specific framework in nuget.

**Comment by Thraka** [comment]
BTW, check at the bottom of the repo, the readme has some migration information

**Comment by Thraka** [comment]
I'm leaving town in 15 minutes.. I'll have my phone for questions. Best way to ask questions would be to post on the sadconsole reddit https://www.reddit.com/r/sadconsole/

**Comment by arxae** [comment]
Oh, didn't know there was a subreddit, time to fill it up then :P

**Comment by Thraka** [comment]
I'm going to work on a nice long blog post this weekend and post on the roguelike reddit and link out to the subreddit too. Help build the community. I also have some neat Python stuff coming 😀

**Comment by Thraka** [comment]
Fixed. I reduced the actual target frameworks to match the MonoGame and SFML specifically. MonoGame is 4.5 and SFML is 4.0
