### ISSUE TITLE
Reduce Allocation in Mouse Processing

### ISSUE THREAD

**Issue by Chris3606** [Thraka/SadConsole#301]
# Background
Some mouse handling questions came up on the SadConsole Discord, and while looking at helping answer those, I ended up perusing through the SadConsole mouse processing implementation.

As far as I can tell, there are a few GCed allocations that appear to happen fairly frequently in the game loop for the sake of handling mouse input, which could (in theory) be mitigated:

1.  [`MouseStateScreenObject` objects are re-allocated](https://github.com/Thraka/SadConsole/blob/335ad0e36728b6f44deb417c70103398276135ae/SadConsole/Input/Mouse.cs#L203), here and in the other condition arms below that line, as well as in various `ScreenObject` implementations.  This is presumably happening per-frame, if mouse input handlers are registered; multiple times a frame if there are are multiple screen objects in a hierarchy and `IsExclusiveMouse` isn't set.

2. During the creation of these `MouseStateScreenObject` objects, [`Clone()` is called on `mouseData`](https://github.com/Thraka/SadConsole/blob/master/SadConsole/Input/MouseScreenObjectState.cs#L58), which is a reference type.

3. During the `Mouse.Update` function (also presumably called once per frame), [an interface is created and returned from the game host](https://github.com/Thraka/SadConsole/blob/335ad0e36728b6f44deb417c70103398276135ae/SadConsole/Input/Mouse.cs#L93) to reflect the mouse state.  The implementations of this interface in both existing back-ends are reference types.  In the case of MonoGame, the `GetMouseState()` function of its game host allocates/returns a new object instance on every call; so this allocation is also being performed per-frame.  It is worthy of note that the underlying mouse-state-retrieval function for MonoGame returns a struct; so SadConsole is adding allocation overhead here.

At least notionally, it appears that at least some of these heap allocations aren't strictly necessary (although fixing them probably requires breaking changes).  I have not benchmarked mouse processing, and therefore have no concrete statistical evidence that these allocations result in reduced performance for any practical use case; however I believe there are a few things that make them a reasonable target to at least benchmark and/or investigate making improvements to:

1. These allocations could happen very frequently; potentially multiple times per frame.

2. They are relatively small in terms of size; and small, frequent allocations tend to create GC pressure, and are often better suited as value types.

3. The user has very little control over most of these portions of mouse processing, so the overhead of these allocations is an issue for some use case, a user doesn't really have any practical methods to resolve the issues.

# Improvements
These concepts are also very notional currently, as I haven't dug through the mouse handling code (and all its use cases) in detail.  However, the following attempts to describe ways to reduce these allocations which, at least at first glance, seem plausible, without changing massive portions of the input handling system.

## `MouseStateScreenObject` creation per-frame: (number 1 from above)
In theory, the `MouseStateScreenObject` class could be made into a value type.  On one hand, it has quite a few fields which together produce a notable size, and it is intended to be passed down through (possibly multiple) screens in the active hierarchy; and these traits together don't always make a prime candidate for a value type.  On the other, as it is currently, new instances are being allocated basically per screen object, so if they're going to be allocated anyway, a value type should provide better performance.

An alternate approach, would be to keep it a reference type, but provide a `SetInfo(params, here)` function which "initializes" it similar to the constructor does now.  This would allow you to re-use one instance of this class; however since currently consoles sometimes allocate new instances of this class and pass them around to children and the like, this could be somewhat dangerous.

## `Mouse` objects being cloned every time a `MouseStateScreenObject` is created (number 2 from above)
I'm assuming there's a reason the state is cloned, rather than the original object just referenced; however I'm not familiar enough with mouse handling to confidently validate this.  However, assuming the clone is purposeful, you could simply use a `MouseData` value type which contains all the public fields from `Mouse` which are copied to the Cloned object in [the current clone implementation](https://github.com/Thraka/SadConsole/blob/335ad0e36728b6f44deb417c70103398276135ae/SadConsole/Input/Mouse.cs#L295).  The object largely just contains boolean values, so they should fit into a value type nicely.

## `IMouseState` objects being allocated per-frame (number 3 from above)
There are two ways I can think of to solve this; the most obvious, is to simply cache the reference type in the back-end's game host implementations, and have `GetMouseState` returned the cached object.
The SFML game host already does this, and in the case of [ the MonoGame back-end's `Mouse` class](https://github.com/Thraka/SadConsole/blob/develop/SadConsole.Host.MonoGame/Mouse.cs#L8), changing the value of the `_mouse` field (which is a value type) on some pre-allocated instance then returning that each time `GetMouseState` is called, is almost certainly easier on the GC than allocating an entirely new reference type per frame.

The other option would be to have a `MouseState` value type which contains all the properties in `IMouseState` as fields, and ditch the interface entirely; but this probably isn't ideal since the mouse state is based on the underlying back-end's state; so fields instead of properties could cause desyncs.

Like I said, not sure to what degree these allocations affect performance, but it certainly looks like an area where they could make a difference.  If there's appetite for it, I can try to PR some benchmarks and/or some changes to v10 which would help mitigate these.

**Comment by Chris3606** [comment]
Edited the above to correct assertions about the `GetMouseState()` functions for existing game-host.

**Comment by Thraka** [comment]
Addressed number 1 and 2. I don't think 3 is really needed and really isn't worth the effort to redesign everything.
