### ISSUE TITLE
ICellSurface ShiftDown doesn't set the background color of the new row correctly.

### ISSUE THREAD

**Issue by RychuP** [Thraka/SadConsole#303]
ShiftDown extension method doesn't set the background of the new row correctly.

![SurfaceShifting](https://user-images.githubusercontent.com/60892050/212520952-8112a4ec-bebb-4c7a-bda8-6bbb8bb799db.gif)

https://github.com/RychuP/SadExperiments/blob/master/SadExperimentsV9/TestConsoles/SurfaceShifting.cs

**Comment by Chris3606** [comment]
Interesting.  I did a PR for [row-shifting methods](https://github.com/Thraka/SadConsole/pull/284) quite awhile back, and those appear to work correctly; I wonder if some of the work done there could be used to fix these and also cut down on what initially looks to be some rather excessive allocation within the shift methods?

**Comment by RychuP** [comment]
It's the only one out of all the Shift methods that uses:

`ColoredGlyph source = surface[y * surface.Width + x];
source.Clear();`

rather than:

`Clear(surface, x, y);`

when clearing the new rows without wrap set to true.
That's all it is I think.

**Comment by Chris3606** [comment]
Yes, it's the difference in clear method that causes this, just verified.  I'll try and PR a fix for this, unless you're intending to?  I would like to write some performance tests for the methods anyway.

**Comment by RychuP** [comment]
It's fine, you carry on. It really is just a one liner.
