### ISSUE TITLE
Left click on a TextBox causes both EditModeEnter and EditModeExit events to trigger.

### ISSUE THREAD

**Issue by RychuP** [Thraka/SadConsole#312]
As per title.

**Comment by RychuP** [comment]
_EditModeExit_ is triggered in _Focused()_ method by _DisableKeyboard = true;_
I believe it should be set to _false_.

**Comment by Chris3606** [comment]
I took a quick look through the source:
- Setting [DisableKeyboard](https://github.com/Thraka/SadConsole/blob/620ca7a7838fb9e176e20de6a2c197868ea35f2e/SadConsole/UI/Controls/TextBox.cs#L121) to `true` triggers `EditModeExit`, `false` triggers `EditModeEnter`.
- [OnLeftMouseClicked](https://github.com/Thraka/SadConsole/blob/620ca7a7838fb9e176e20de6a2c197868ea35f2e/SadConsole/UI/Controls/TextBox.cs#L539) sets this property to `false`.  This would trigger `EditModeEnter`.
- Later on in `OnLeftMouseClicked`, the text box is set to the focused object.  This should ultimately trigger [Focused()](https://github.com/Thraka/SadConsole/blob/620ca7a7838fb9e176e20de6a2c197868ea35f2e/SadConsole/UI/Controls/TextBox.cs#L524), which sets `DisableKeyboard` to `true`.  This will trigger `EditModeExit`.

It seems odd to me that `Focused()` is setting `DisableKeyboard` to `true`; I would expect it to also set `false`, so as to trigger the edit mode enter event.  Even if it did, though, it looks like it would end up triggering `EditModeEnter` twice on click; once in `OnLeftMouseClick`, and once in focus.  Probably there should be some sort of guard on one or more of these properties to prevent this.

**Comment by Thraka** [comment]
Edit mode was removed in v10 so this bug is technically fixed 😁
