### ISSUE TITLE
ComboBox dropdown doesn't take FontSize of parent in consideration

### ISSUE THREAD

**Issue by Ven0maus** [Thraka/SadConsole#318]
When the parent screenobject has a different fontsize than the _dropDownContainer, the position is wrong.
Fix would be something like this:

```
_dropDownContainer.FontSize = ((ScreenSurface)_dropDownContainer.Parent).FontSize;
```

**Comment by Thraka** [comment]
Fixed in https://github.com/Thraka/SadConsole/commit/449ddc7430dc490c95e976c13321b2e36cc7d031
