### ISSUE TITLE
When keyboard input is changed, the controls system is affected

### ISSUE THREAD

**Issue by Thraka** [Thraka/SadConsole#33]
If you change the keyboard delay and repeat settings on `SadConsole.Engine.Keyboard` controls like the TextBox will be affected. Fast settings make it too hard to type like a normal keyboard.

Found while testing out a project from @arxae

**Comment by Thraka** [comment]
This will make it into NuGet soon.

**Comment by arxae** [comment]
Oh yeah, i just noticed that. But how did you test that? I remade the repo, and i didn't use input boxes at that time :P

**Comment by Thraka** [comment]
your `TerminalConsole` is using it.

**Comment by arxae** [comment]
Yeah i mixed some stuff up. I replaced the repo with a new one, thought you saw it in the old one (which didn't have the terminal yet)
