### ISSUE TITLE
Question about rendering raster images

### ISSUE THREAD

**Issue by 0zl** [Thraka/SadConsole#348]
Hello,

I recently found SadConsole while looking for a retro console game engine, and I'm loving it so far!

I'm kinda stuck on the graphics side though. Is there any tutorials or docs on rendering raster images? Specifically, I wanna add character portraits, maybe in a layout or something.

I had this idea to chop up the portrait into `16x8` or `16x16` pixel chunks and use those as fonts. But then I saw that the fonts need to be pure white (#FFF) instead of colored. Also, if I'm doing this, I won't be able to make any procedural characters.

```
The image file of the font must use a transparent background, and not a colored key file. The glyphs in the font graphic should use a pure white color (255, 255,255) for the foreground.

- https://sadconsole.com/articles/systems/fonts.html
```

Just to be clear, this isn't an issue, just a question! I'm sorry if I post this on issue tab.
Awesome project btw, keep it up!

**Comment by Thraka** [comment]
Hi @0zl 

We have a good sized discord group if you want to join. I got this new issue alert in discord 😁 

You could totally do this by hacking a font, like you were suggesting. The restrictions in the font article are really only there for when you recolor the glyphs in the font. For example, if you were coloring a cell in a surface with the foreground of green, green is applied to every non-transparent pixel in the font glyph. If that pixel isn't pure white, then the output is the existing pixel multiplied by the green foreground, so it may not look like the desired effect. This is why color key's don't work, and the shading system expects transparency as the background so things look correct. If you use the color white as the foreground of a cell, white, nothing is applied to the pixels, and they're just rendered as-is. This means you can have full color in the font file, and it will look exactly as expected. You can even mix-and-match, having some things colored, some things pure white, or some things using a white-to-black shade. You just need to know what you're working with so you apply your foreground colors correctly.

The other major restriction to font files is defining a solid white rectangle. This is ONLY to support setting the background of a surface cell to something other than transparent. When you fill the background of a cell, it's actually printing that solid white glyph defined by the font, and then shading it. This keeps the foreground and background drawing scheme within a single font file, and means the calls to the graphics card are batched for high performance.

With that little bit of history, there is a way to draw images 😁 Use the `SadConsole.Components.DrawImage` component. Attach it to an existing `IScreenSurface` and you can position it pixel or to a specific cell position within that console. The `PositionMode` property sets pixel or cell positioning, and the `PositionOffset` is the position to draw the image based on the mode and the position of the parent hosting object. If the object is a `IScreenObject`, meaning it has no font or surface itself (unlike the `IScreenSurface`) you can only use pixel positioning.
