### ISSUE TITLE
REXPaint IndexOutOfBoundsException

### ISSUE THREAD

**Issue by snakemeat** [Thraka/SadConsole#39]
Hi, finally back to trying to get a game going and am re-familiarizing myself with your library.  I updated from nuget tonight (4.1.2-pre7) based on some interesting looking stuff from reddit.   

Tonight I decided to test the REXPaint integration.  I created a simple file using REXPaint v1.03 (attached).

I tried to create a simple console class that includes the the following code in the constructor:
```
            Image InputTemplate;
            string inputPath;

            // Load REXPaint Template
            inputPath = ConsoleConstants.RexPaintFilePath + "InputFrame.xp";

            using (FileStream fs = File.OpenRead(inputPath))
            {
                InputTemplate = Image.Load(fs);
            }

            // Write REXPaint image to this consoles surface
            this.TextSurface = InputTemplate.ToTextSurface();
```

I get the following exception when calling ToTextSurface():

`ArgumentOutOfRangeException was unhandled
  HResult=-2146233086
  Message=Specified argument was out of the range of valid values.
Parameter name: index
  ParamName=index
  Source=SadConsole.Core.Windows
  StackTrace:
       at SadConsole.Consoles.LayeredTextSurface.SetActiveLayer(Int32 index)
       at SadConsole.Consoles.LayeredTextSurface..ctor(Int32 width, Int32 height, Font font, Int32 layers)
       at SadConsole.Consoles.LayeredTextSurface..ctor(Int32 width, Int32 height, Int32 layers)
       at SadConsole.Readers.REXPaint.Image.ToTextSurface()`

The InputTemplate object has the following values:

```
-		InputTemplate	{SadConsole.Readers.REXPaint.Image}	SadConsole.Readers.REXPaint.Image
		Height	0x00000003	int
		LayerCount	0x00000000	int
-		Layers	Count = 0x00000001	System.Collections.ObjectModel.ReadOnlyCollection<SadConsole.Readers.REXPaint.Layer>
-		[0]	{SadConsole.Readers.REXPaint.Layer}	SadConsole.Readers.REXPaint.Layer
+		Cells	Count = 0x000000f0	System.Collections.ObjectModel.ReadOnlyCollection<SadConsole.Readers.REXPaint.Cell>
		Height	0x00000003	int
		Width	0x00000050	int
+		Non-Public members		
+		Raw View		
		Version	0x00000001	int
		Width	0x00000050	int
+		Non-Public members		

```
[InputFrame.zip](https://github.com/Thraka/SadConsole/files/428687/InputFrame.zip)

**Comment by Thraka** [comment]
Thanks for the amazing bug report. Fixed it in the soon to be released 4.2.0 nuget package.

**Comment by snakemeat** [comment]
Hi, thanks for fixing the exception.  I'm now experiencing a new issue related to the rendering of the file.

In REXPaint, the file looks like the attached image, "rex.png."  When rendered via SadConsole, it looks like "sad.png."

Thinking it was related to the font, I copied the font cp437_12x12.png from REXPaint, and created a .font file to match (see cp437.zip).

I'm not sure if I'm doing something wrong,  Any ideas?

![rex](https://cloud.githubusercontent.com/assets/12780987/17842145/a69a287c-67d4-11e6-954b-110bc35315d4.png)
![sad](https://cloud.githubusercontent.com/assets/12780987/17842201/1ad59438-67d5-11e6-9473-d5a4e79cceb1.png)
[cp437.zip](https://github.com/Thraka/SadConsole/files/429261/cp437.zip)

**Comment by Thraka** [comment]
sigh.. I know what the problem is.. brb

**Comment by Thraka** [comment]
fixed on nuget.

**Comment by snakemeat** [comment]
Thanks!  Working here now.
