### ISSUE TITLE
Font Handling Enhancements

### ISSUE THREAD

**Issue by tstavrianos** [Thraka/SadConsole#44]
I wasn't sure if this is something that should be an Issue or if I should have made a pull request instead.

In Font.cs on line 116 (and again on 303, 307, 308) you reference Engine.FontColumns (which has a constant value of 16). Can that be switched to a Columns property that works identical to Rows from FontMaster?

Also is it possible to include a constructor for FontMaster to initialise from a Texture2D (including parameters for the character width/height and font name)?

My aim with both changes is to allow me to pre-process a font file dynamically and allow me to support more layout formats, without having to convert the files (support the layouts from TCOD for instance). All the processing would happen on the Texture (which can be either SFML or MonoGame based), which I can then feed into the FontMaster.

Sorry if this should be a PR instead, first time posting here

**Comment by Thraka** [comment]
A PR would only be useful if you had made the code changes to support this and wanted to get that integrated into the main repository.

This is a great suggestion and one I've thought about for a long time. I'm getting close to merging my existing develop branch into the master and doing a new nuget release. This update mainly focuses on serialization fixes. Once I get this out the door (today most likely) I'll get started on this.

**Comment by Thraka** [comment]
This is now in the main branch. I'll be doing a release later today so just update your NuGet package.

`Engine.FontColumns` no longer exists and there is a constructor for FontMaster that lets you pass in font information, including the texture.

Thanks for the suggestion.
