### ISSUE TITLE
NuGet porting?

### ISSUE THREAD

**Issue by tgiachi** [Thraka/SadConsole#5]
Hi!, great library! Is possibile to update to monogame 3.2 and publish to NuGet?

Thank you!!

**Comment by Thraka** [comment]
Is it not using 3.2? I thought I was. Regarding NuGet, I have no idea how to create a package for that. It may new a few weeks before I have time to look at doing that. 

Thanks for the suggestion!

**Comment by tgiachi** [comment]
I'm sorry! I mean MonoGame 3.3!! If you want I'll publish packages for you!

**Comment by Thraka** [comment]
OK Sure, I'll look into that. OK, If you want to start getting together the required information for building a NuGet package, I'll get you binaries by tonight (hopefully) :)

https://github.com/mono/MonoGame/issues/3749

**Comment by eropple** [comment]
One thing that might help is moving away from using the packaged binaries and using the NuGet MonoGame packages; I've moved to that for my own stuff and been really happy with the experience. It should aid with porting, too, as there are MonoGame NuGet packages for Windows, MacOS, and Linux.

If you're comfy moving to 2013/2015-only, you could use a shared project to encapsulate application code and handle the references in the endpoint projects.

**Comment by eropple** [comment]
This is handled in #6.
