### ISSUE TITLE
Font does not exist?

### ISSUE THREAD

**Issue by cuteloligrill** [Thraka/SadConsole#50]
fresh download, and when using the startup guide Program.cs for(both mono and SFML), I get the following error:
`An unhandled exception of type 'System.Exception' occurred in SadConsole.Core.Windows.dll

Additional information: Font does not exist: IBM.font`

**Comment by Thraka** [comment]
Got this working then?

**Comment by cuteloligrill** [comment]
Yes, it was an issue on my part, files were not set to save to output
