### ISSUE TITLE
Part three of the wiki Tutorial no longer works

### ISSUE THREAD

**Issue by Vzor-** [Thraka/SadConsole#66]
CellsRenderer was replaced with TextSurfaceRenderer and CellSurface was replaced by TextSurface

**Comment by Thraka** [comment]
Ack, thanks.

**Comment by Thraka** [comment]
Looks like that code was actually old and should have been removed. That variable was declared twice, whoops.

**Comment by Vzor-** [comment]
Thanks a lot, I have another issue but it may just be a coding mistake (so I don't want to make a new issue). On win10, when I minimize my window then open it, the window is tiny.

**Comment by Thraka** [comment]
oh no... verified. Do you want to open up a new issue? I'll start fixing it and get a nuget update out

**Comment by Vzor-** [comment]
ok, ill open an issue.
