### ISSUE TITLE
Minimized windows restore too the wrong size

### ISSUE THREAD

**Issue by Vzor-** [Thraka/SadConsole#67]
On windows 10 (and maybe others) when a window is minimized then restore it, it restores to a tiny window; only about 100px*64px.

**Comment by Vzor-** [comment]
On a side note, is there a way to get reference to the window? I would like to make my application resizable if possible

**Comment by Thraka** [comment]
When you call init, use this code (assuming you're using MonoGame)

    SadConsole.Engine.Initialize("IBM.font", 80, 25, (g) => { g.Window.AllowUserResizing = true; });

To get the window at any time in the future, use this `SadConsole.Engine.MonoGameInstance.Window`. However, this isn't a "winforms window" it's a MonoGame Window, a abstracted-platform independent window. You would have to convert the handle (`SadConsole.Engine.MonoGameInstance.Window.Handle`) to the appropriate platform (mono/windows) window type.

**Comment by Thraka** [comment]
Fixed in f37a926

**Comment by Thraka** [comment]
NuGet is updated. It may take a few mins to show up.
