### ISSUE TITLE
Window Resizing

### ISSUE THREAD

**Issue by mxmissile** [Thraka/SadConsole#7]
What is the proper way to handle window resizing? 

` Window.AllowUserResizing = true;`

Setting that to true, the window re-sizes fine but the mouse pointer gets offset.

Is there something I need to do in the  `Window_ClientSizeChanged` event?

**Comment by Thraka** [comment]
I've never actually tried that. I'll look into it.

**Comment by Thraka** [comment]
Yes, you just need to set the `WindowWidth` and `WindowHeight` properties on the engine.

```csharp
Engine.WindowWidth = manager.PreferredBackBufferWidth; 
Engine.WindowHeight = manager.PreferredBackBufferHeight; 
```

The `manager` variable is the `GraphicsDeviceManager`.

Let me know if this works

**Comment by Thraka** [comment]
@mxmissile Ping

**Comment by mxmissile** [comment]
Been out of town. I'll check it out next weekend.

**Comment by Thraka** [comment]
No worries :) Just making sure you saw

**Comment by Thraka** [comment]
@mxmissile Ping
