### ISSUE TITLE
FullScreen + Controller Support

### ISSUE THREAD

**Issue by ashes999** [Thraka/SadConsole#70]
Hi,

According to [this wiki page](https://github.com/Thraka/SadConsole/wiki/Working%20with%20Input), SadConsole doesn't yet support controllers.

Based on [the last section of this tutorial](http://www.gamefromscratch.com/post/2015/06/28/MonoGame-Tutorial-Handling-Keyboard-Mouse-and-GamePad-Input.aspx), it looks fairly trivial to poll MonoGame for controllers.

Is there any way I can include controller support in my game, without waiting for a release of SadConsole with controller support? Maybe I can use MonoGame APIs directly?

**Comment by Thraka** [comment]
Yeah I guess that is a bit misleading. Since it uses MonoGame, you can do anything MonoGame can do, like using controllers. I just haven't implemented anything in SadConsole to hook that. For example, right now when you press the keyboard, you get a specific method called about keyboard input updates. I would envision the same thing for controllers.

So as it stands right now, you would have to do all that yourself. Most likely you want to do this on the Update part of the console itself or globally through the `SadConsole.Engine.EngineUpdated` event.

**Comment by ashes999** [comment]
Okay, thanks, that's what I suspected.

**Comment by Thraka** [comment]
Feel free to share back code when/if you do controller support :)

**Comment by ashes999** [comment]
I actually discovered that SadConsole doesn't have a full-screen mode! Console support is pretty useless without that .. sorry :)

**Comment by Thraka** [comment]
It does!

**Comment by Thraka** [comment]
I added it in about 2 weeks ago due to request. Use `SadConsole.Engine.ToggleFullScreen();` 😁

**Comment by ashes999** [comment]
Oh no...

Is this available in SadConsole.Core.MonoGameGL v5.2.2 on NuGet?

**Comment by ashes999** [comment]
Is this available in SadConsole.Core.MonoGameGL v5.2.2 on NuGet?

**Comment by Thraka** [comment]
It should be.

**Comment by Thraka** [comment]
The GL library of monogame may have problems with fullscreen though. I remember commenting on an issue in the monogame repository about this. I'll try and find it

**Comment by Thraka** [comment]
Sure enough, it's true. The GL version of MonoGame seems to hate the fullscreen stuff. The DX version works fine. The MonoGame repository seems to have a lot of issues fixed regarding it, however, nuget for monogame is almost 1 year old. I'm not sure when they are planning to update nuget. I'll see if I can add something into SadConsole to fix the problem for GL.

**Comment by ashes999** [comment]
This is interesting.

I can build and run with 5.0.8 on Linux and Windows. With 5.2.2, Windows runs with a "platform not supported" exception, and Linux fails to build.

It's probably something on my side. I'll try this again later and update this issue if I figure anything out.

**Comment by ashes999** [comment]
Okay, so I got this working on Linux (not sure what changed). Where do I call `ToggleFullScreen`? If I do it after `SadConsole.Engine.Run()`, it doesn't appear full-screen. If I call it before, I get an "Object reference not set" (null reference/pointer) exception.

**Comment by Thraka** [comment]
Try in 
```
private static void Engine_EngineStart(object sender, EventArgs e)
{
    SadConsole.Engine.ToggleFullScreen();
```

**Comment by Thraka** [comment]
Updated my comment above in case you didn't see it.

**Comment by ashes999** [comment]
Hi,

I can confirm that adding it to `Engine_Update` works (I already had this from some other tutorials). On Ubuntu. With proper full-screen. So I don't know what MonoGame full-screen issues you're talking about, because things appear to work for me.

That said, full-screen is ... not great. I was hoping for something like "scale up to fit your display device," but this will do. (For reference, I may experiment with running this on something like a Raspberry Pi which is hooked up to a 1080p TV.)

I'll see if I can look at gamepad support over the next couple of days.  Thanks for being so active on this issue.

**Comment by Thraka** [comment]
No problem 😄 glad to help!

By default it should scale to fit correctly and look great. This may be part of what is broken on the Linux side. The Windows GL fullscreen is 90% broken for me though.

The MonoGame team has definitely worked on the GL fullscreen problems, just not released them yet. You can always pull down their develop branch code and compile the latest GL library and copy/paste it to your output to see if it fixes the issues for you.

Basically, you have to get MonoGame to some how play nice. You can try this code, it helped on windows gl but wasn't perfect. If I did a "after I'm fullscreen, I toggle to windowed" it didn't look right any time after.

```
SadConsole.Engine.Initialize("IBM.font", 80, 25, (g) => 
    {
        g.Window.IsBorderless = true;
    });
```
and

```
private static void Engine_EngineStart(object sender, EventArgs e)
{
    Engine.DeviceManager.PreferredBackBufferWidth = Engine.Device.DisplayMode.Width;
    Engine.DeviceManager.PreferredBackBufferHeight = Engine.Device.DisplayMode.Height;
    Engine.DeviceManager.ApplyChanges();
    Engine.ToggleFullScreen();

    ...
```

I'm actually in the middle of a complete refactor that changes the backend rendering system (half of this work originated from the current nuget sadconsole to get fullscreen and scaling working) which will enable you to work around these issues by cutting out parts of SadConsole if you need to.

**Comment by ashes999** [comment]
I'm not in a rush to get this working. Having "any" fullscreen thing working is fine.

Again, for development, I work non-fullscreen with the regular-sized window (on Linux). I will occasionally, experimentally deploy to my Linux device which hooks up to my 1080p TV, and run it full-screen -- most likely through the use of some command-line option like `--fullscreen` that calls `Engine.ToggleFullScreen()` once and only once on `EngineStart`. I won't need to ever switch back to windowed.

This is just a fun experiment for me. I'm primarily going to develop/play on Linux in windowed mode, without a gamepad. I have basically enough knowledge now to expect this to work in some (perhaps distant) future version of SadConsole, without me doing anything ... that's more than good enough for my needs.

I can wait, a long time if necessary :)

Cheers,

**Comment by Thraka** [comment]
Sounds good :)

**Comment by ashes999** [comment]
I got this working. It looks like the gamepad support is (mostly) as easy as a copy/paste of the code from the tutorial in my first post.

Problem is, it doesn't take into account `SadConsole.Engine.Keyboard.RepeatDelay` and `SadConsole.Engine.Keyboard.InitialRepeatDelay` -- the player literally zooms across the screen.

You can see the earliest version of this code [in this method](https://github.com/deengames-prototypes/cataclysm/blob/be8f0d7c5372653ad108b042e0c28e7ec8c77b0b/Cataclysm/Consoles/AreaViewConsole.cs#L94). It would be nice to add native support, or for a PR ... but please don't hold your breath :)
