### ISSUE TITLE
ITextSurfaceRenderer.Render() should use BlendState.AlphaBlend by default

### ISSUE THREAD

**Issue by TheMostCuriousThing** [Thraka/SadConsole#73]
ITextSurfaceRenderer.Render() currently doesn't respect semi-transparency in font textures (including the Cheepicus12 font included in SadConsole) because it uses BlendState.NonPremultiplied.

[Image reference](http://imgur.com/a/Chnzp)

**Comment by Thraka** [comment]
Doh! I had this long ago and must have removed it at some point. This will be fixed in the upcoming major release.

**Comment by Thraka** [comment]
In some quick tests there are some oddities between OpenGL, DirectX, and Android. Setting the blend state to alpha makes DirectX work perfect, OpenGL and Android don't seem to care. Using the latest dev version of MonoGame OpenGL, it's a bit better but still doesn't match DirectX.

Will continue to investigate.

**Comment by Thraka** [comment]
DirectX will support this correctly. OpenGL may have to wait for the next public release of MonoGame (or your game will have to at least use the preview build)

Will be in PR #72
