### ISSUE TITLE
Example project(s?) don't work

### ISSUE THREAD

**Issue by Fortnox** [Thraka/SadConsole#75]
I just tried checking downloading the repo, opening the sln and running the Castle example. It breaks on MonoGameEngine:87 because MonoGameInstance hasn't been instantiated. 

There are a number of Initialize methods and one of them does set MonoGameInstance. If you copy that line, MonoGameEngine:157, and paste it at the top of the Initialize method in use (MonoGameEngine:55) then Castle runs perfectly.

I've only tested this with Castle, but I suspect it affects the others too. It looks like there was some sort of oversight or flawed VC conflict resolution? Tested on Win 10, VS2015

**Comment by Thraka** [comment]
Sorry! There was a bug introduced with using your own Game class versus the built in SadConsole game class. These example projects were originally created with a Game class.  I fixed this issue in my engine-rewrite branch but that branch also changes a bunch of structure, namespaces, variable names etc. So all the tutorials will have to be rewritten when I publish that branch.

However, you're the 2nd person to mention this to me so I'll go fix that bug itself and publish an update.

Sorry!

**Comment by Thraka** [comment]
OK this is fixed now. Sorry!

**Comment by Fortnox** [comment]
No worries man, you're the one providing this great project. Just started dipping my feet in and it seems really cool.

**Comment by Thraka** [comment]
Thanks! Hopefully the refactor I'm doing will continue to simplify and make things more intuitive to use.
