### ISSUE TITLE
changing application window title

### ISSUE THREAD

**Issue by erikyuzwa** [Thraka/SadConsole#78]
Since SadConsole is taking over the creation of the ApplicationWindow, can I change the title via API?

**Comment by Thraka** [comment]
Yes, MonoGame provides you access to the Window. I've stuffed the game instance in `SadConsole.Engine.MonoGameInstance`.

```
SadConsole.Engine.MonoGameInstance.Window.Title = "My new title";
```

**Comment by erikyuzwa** [comment]
oh boy - :embarrased: thanks!
