### ISSUE TITLE
REXReader not displaying correctly

### ISSUE THREAD

**Issue by snakemeat** [Thraka/SadConsole#8]
@Thraka Thanks for the extensive library.  I'm considering making a procedurally generated text rpg and your library has a lot of nice options.  I'd like to develop a few screens (menu, game screen, etc.) in REXPaint and then import them to add values.  To test, I made a simple two layer REXPaint.xp image (attached), using REXPaint 0.99r9.

Rendering using REXReader does not produce the same result as the opening in REXPaint.  I used the following code:
```
            SadConsole.Readers.REXPaint.RexReader reader = new SadConsole.Readers.REXPaint.RexReader("...\test.xp");
            var tileMap = reader.GetMap();            
            var console = tileMap.ToLayeredConsole();

            SadConsole.Engine.ConsoleRenderStack.Add(console);
            SadConsole.Engine.ActiveConsole = SadConsole.Engine.ConsoleRenderStack[0];
```

Am I missing a step or is it something else (magenta vs transparent)?  Thanks again.
[test.zip](https://github.com/Thraka/SadConsole/files/55034/test.zip)

**Comment by Thraka** [comment]
I'll check it out. Thanks for the complements :) I also have a native editor for SadConsole [here](https://github.com/Thraka/SadConsoleEditor) and a [video](https://youtu.be/ZukjZIqDfJw?t=276)

**Comment by Thraka** [comment]
OK Fixed in the latest source. Use:

```csharp
SadConsole.Readers.REXPaint.RexReader reader = new SadConsole.Readers.REXPaint.RexReader("...\test.xp"); 
var console = reader.ToLayeredConsole();

SadConsole.Engine.ConsoleRenderStack.Add(console);
SadConsole.Engine.ActiveConsole = SadConsole.Engine.ConsoleRenderStack[0];
```
There is a bug in the REXReader for C# that I'm using the code from. This just bypasses that whole reader and only uses it for loading the xp file into memory.

**Comment by snakemeat** [comment]
Thanks, working great now.
