### ISSUE TITLE
Unable to add SDL2.dll to Visual Studio 2017 project

### ISSUE THREAD

**Issue by sbowman** [Thraka/SadConsole#82]
Admittedly I'm a bit new to C# development, but in following your tutorial, I was unable to add any SDL2.dll file to my VS 2017 project.  I tried the one from your link, as well as the 32-bit and 64-bit DLLs from the SDL2 site directly.  Every time I get the message:

"A reference to <...the SDL2 file path> could not be added.  Please make sure the file is accessible, and that it is a valid assembly or COM component."

Also tried messing with the .NET Framework version, and even trying the sdl2 Nuget package, but nothing worked.

**Comment by Thraka** [comment]
Not sure exactly how you're doing it. Was it [these directions](https://github.com/Thraka/SadConsole/wiki/NuGet-Starter-MonoGame) (step 4 important note) that you followed?

**Comment by sbowman** [comment]
Was working from that page.  Deleted my project and started fresh, just to make sure I didn't skip any steps.

* Created a Visual C#, Windows Classic Desktop, Empty Project (.NET Framework)
* Selected "Manage NuGet Packages...", "Browse", and installed SadConsole 6.0.1
* Then searched for "MonoGame" and selected MonoGame.Framework.DesktopGL 3.6.0.1625
* Clicked on your download link, downloaded SDL2.dll, and copied it to the same directory as the fonts, program-example.cs, etc.
* Right clicked on the project, then select Add > Reference
* Clicked "Browse" then "Browse" button and selected the SDL2.dll file
* Clicked "Add"
* Got this dialog:

![image](https://cloud.githubusercontent.com/assets/47979/24086006/a4086f54-0ccc-11e7-984b-b6137bb65ec1.png)

Earlier today I also tried the 64-bit DLL from the SDL2 project, but that had the same results.

**Comment by sbowman** [comment]
I also noticed VS 2017 defaults to .NET Framework 4.5.2.  Is this not the correct .NET Framework version?

**Comment by sbowman** [comment]
Installed MonoGame 3.6 using the installer, then created a new MonoGame project using DesktopGL.  Everything worked fine (it automatically included the SDL2.dll in its project template).

**Comment by Thraka** [comment]
OH WAIT... man I think my steps are wrong. You add it to your project as a FILE, not a reference. then you set it to COPY TO OUTPUT. argg!  :) I wish MonoGame would have just included it in the nuget package.

**Comment by Thraka** [comment]
Sorry about that. doh!

**Comment by Thraka** [comment]
I just updated the wiki article.

**Comment by Thraka** [comment]
Oh and about 4.5.2, it does't really matter, the difference for 4.6 really only matters if you're creating a universal app and thus can use .NET Native. Otherwise the differences between 4.5 and 4.6 aren't important (in my opinion :smile:)

**Comment by sbowman** [comment]
Thanks for all this.  Wasn't able to get to it until tonight, but I wanted to let you know (a) it worked, and (b) how appreciative I was.

**Comment by Thraka** [comment]
Thanks for helping me find the error in the important startup article!!
