### ISSUE TITLE
EntityBase constructor base() call missing parameter (1,1) on wiki

### ISSUE THREAD

**Issue by HooniusDev** [Thraka/SadConsole#83]
Project files have the correct version, its the text tutorial having the issue

Also the player constructor is using '@', when EntityBase expects an integer. this is in both the wiki and downloaded Project files

Ok, dont know if I should open up a new issue for all of these, but found another error.

At the end of part 2 you tell to add IsTileWalkable method to MapConsole.cs but it should go into Map.cs

**Comment by Thraka** [comment]
Thanks! Indeed. I must have changed that code after I wrote that part of the tutorial. I've updated the tutorial and the code .zip file. Thanks for the report!
