### ISSUE TITLE
Subconsoles

### ISSUE THREAD

**Issue by aaronmell** [Thraka/SadConsole#87]
I'd like to do something like the RogueSharp tutorial, where I have separate consoles for the map, message log etc. that are all indepent of one another, and drawn on separately.  Whats the best way to achieve this?

**Comment by Thraka** [comment]
The `Global.CurrentScreen` is what gets drawn. By default it's a basic empty `Screen` type. You can create a console, and add it to the children collection `Global.CurrentScreen.Children.Add(myconsole)`. As many consoles you have in there, will be drawn. You just size and position each one so they are not overlapping. I've been meaning to continue working on the new roguelike tutorial but I just haven't had the time with doing support and updating the editor tool.

**Comment by aaronmell** [comment]
hmm, I tried this, and it didn't seem to work right. I'll give it another go.

**Comment by Thraka** [comment]
Let me know.
