### ISSUE TITLE
NPE in ControlConsoleRenderer.Render(...)

### ISSUE THREAD

**Issue by akuseku** [Thraka/SadConsole#94]
Hi,
When using a `ControlConsole`, the` ControlsConsoleRenderer` cannot be used to render a surface before the first call to `ControlConsole.Draw(...)` as `ControlsConsoleRenderer.Controls` is only initialized then.

This requires to initialize `ControlsConsoleRenderer.Controls` to an empty list or to use another Renderer if you want to render a surface before any draw calls. (eg. rendering a border in the constructor)

Having `ControlsConsoleRenderer.Controls` initialized beforehand would make the Renderers of `Console` and `ControlConsole` behave in the same way. But maybe `ControlsConsoleRenderer` isn't really intended to render `BasicSurface` objects as it will also render the Controls that might be present.

**Comment by Thraka** [comment]
Do you mean you're doing custom rendering where you want to reuse the `ControlsConsoleRenderer` prior to the normal usage?

The `ControlsConsoleRenderer` still renders the normal surface of the `ControlsConsole` before the controls are drawn. So you can still draw borders and things.

**Comment by akuseku** [comment]
Exactly! I have a custom `ControlConsole `and wanted to reuse the `ControlsConsoleRenderer` to render a BasicSurface in my console constructor (a border that will be rendered only once).

The `ControlsConsoleRenderer.Render(...)` renders the Cells as expected but it then calls `RenderControls(...) ` on line 29.
The method uses `ControlsConsoleRenderer.Controls` which is still null at this point as it is set by `ControlConsole.Draw(...)` line 402
I checked the value of `ControlsConsoleRenderer.Controls` in the debugger before the rendering call
and it confirms this. Setting it to a new empty List before rendering prevent the NPE from being thrown.

It's not much but I have a small class demonstrating this behavior if you want :)

**Comment by Thraka** [comment]
I'll fix this bug, it should be initialized at the start. 

However, I think you'll have a problem with the `ControlsConsoleRenderer` itself though. It does draw the `.TextSurface` right before controls are drawn, covering the whole area. If you're trying to do a custom border, you should just draw to the console itself. Otherwise, you need to inject drawing inbetween the textsurface and the controls. This would be a new renderer type.

Inherit from `ControlsConsoleRenderer` insert your own render logic.

```csharp
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using SadConsole.Surfaces;
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SadConsole.Renderers
{
    /// <summary>
    /// Draws a text surface to the screen.
    /// </summary>
    [DataContract]
    public class MyControlsConsoleRenderer : ControlsConsoleRenderer
    {

        // Add a new property here that you pass in from your console, this would be data for your custom render routine.

        /// <summary>
        /// Renders a surface to the screen.
        /// </summary>
        /// <param name="surface">The surface to render.</param>
        public override void Render(ISurface surface, bool force = false)
        {
            RenderBegin(surface, force);
            RenderCells(surface, force);

            // Any render code here would draw something after the console draws but before the controls.

            RenderControls(surface, force);
            RenderTint(surface, force);
            RenderEnd(surface, force);
        }

    }
}
```

On your custom `ControlsConsole`, in the `Draw` routine, pass in your own data, just like the `ControlsConosle` does: https://github.com/Thraka/SadConsole/blob/master/src/SadConsole.Shared/ConsoleTypes/ControlsConsole.cs#L402

**Comment by akuseku** [comment]
You're right, I will probably have problems down the road.
Creating a custom Renderer seems more suited to my needs actually.
Thanks!
