### ISSUE TITLE
DllNotFoundException for SDL2 on OSX

### ISSUE THREAD

**Issue by dannytatom** [Thraka/SadConsole#96]
From my understanding, this *should* work on OSX? I've never used C# outside of Unity and never used Visual Studio, so this is probably just me being dumb. I'm using the newer Visual Studio on OSX if that matters.

Following [this page](https://github.com/Thraka/SadConsole/wiki/NuGet-Starter-MonoGame), I did exactly what it said, but still errors out that it can't find SDL2.dll.

**Comment by Thraka** [comment]
My guess is that you need to download the OSX version of SDL2? http://www.libsdl.org/download-2.0.php
