### ISSUE TITLE
Keyboard Input on InputBox not working

### ISSUE THREAD

**Issue by AshkoreDracson** [Thraka/SadConsole#98]
Hello!

I've taken a stab at trying SadConsole by downloading the starter nuget package.
I tried to add a pop-up window from your wiki example on controls to the example file, the InputBox worked.

However now, I modified the program-example.cs to fit my needs, it instantiates multiple Consoles for different screens, and in any of those screens, any InputBox just won't recieve keyboard input anymore.
The event TextChanged and TextChangedPreview aren't even triggered.

I didn't modify anything in regards to keyboard states or anything, just adding controls, filling and printing stuff.

EDIT: I have tried on a brand new project just importing SadConsole & the starter project and adding the example window from the controls wiki, still no keyboard input...

**Comment by AshkoreDracson** [comment]
Apologies I fixed it.

Forgot to set the focused console via `Global.FocusedConsoles.Set(IConsole);`

**Comment by Thraka** [comment]
Maybe I should add that line to the starter to demonstrate that common scenario. 😄  Thanks
